apiVersion: v1
kind: Pod
metadata:
  name: awsbuild-pod
  namespace: <YOUR NAMESPACE HERE>
spec:
  initContainers:
    - name: git-clone-init
      image:  public.ecr.aws/bitnami/git:latest
      env:
        - name: AZ_USERNAME
          valueFrom:
            secretKeyRef:
              name: azure-repo-secret
              key: AZ_USERNAME
        - name: AZURE_PAT
          valueFrom:
            secretKeyRef:
              name: azure-repo-secret
              key: AZURE_PAT
      command:
        - /bin/sh
        - "-c"
        - |
          set -ex
          echo "Ensuring /app/pim is writable..."
          mkdir -p /app/pim
          chmod -R 777 /app/pim
          echo "Checking if /git-temp/pim exists and is not empty..." && \
          if [ -d "/git-temp/pim" ] && [ "$(find /git-temp/pim -mindepth 1 | head -n 1)" ]; then
            echo "/git-temp/pim exists and is not empty. Cleaning up..."
            rm -rf /git-temp/pim
          fi && \
          echo "Cloning repository..." && \
          git clone https://$AZ_USERNAME:$AZURE_PAT@dev.azure.com/Nexus-One/NX1%20Special%20Projects/_git/aws_ad_auth /git-temp/pim && \
          echo "Copying files..." && \
          cp -r /git-temp/pim /app/pim
      volumeMounts:
        - name: git-repo-volume  # Temporary volume for cloning
          mountPath: /git-temp
        - name: awsbuild-storage  # Persistent volume for storing cloned content
          mountPath: /app/pim
  containers:
    - name: awsbuild-container
      image: 410778887951.dkr.ecr.us-east-1.amazonaws.com/msp_ops/azdevops-cdp-jammy-img:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "0.5"
        limits:
          memory: "1Gi"
          cpu: "1"
      volumeMounts:
        - name: awsbuild-storage
          mountPath: /app  # Persistent storage mounted to /app
        - name: awsbuild-storage
          mountPath: /root/.aws  # Additional mount for /root/.aws
          subPath: root-aws  # Specify a subdirectory on the PVC for isolation
  imagePullSecrets:
    - name: ecr-secret
  volumes:
    - name: git-repo-volume
      emptyDir: {}  # Temporary volume to store cloned files
    - name: awsbuild-storage
      persistentVolumeClaim:
        claimName: efs-claim-<YOUR NAMESPACE HERE>
