version: '3.8'

services:
  awsbuild:
    image: amd64/ubuntu:azdevops-cdp-jammy-img
    container_name: aws-ad-auth
    volumes:
      - type: volume
        source: awsadauth_vol1
        target: /app
    command: ["tail", "-f", "/dev/null"]

volumes:
  awsadauth_vol1:
    external: true
