apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-<YOUR NAMESPACE HERE>
  namespace: <YOUR NAMESPACE HERE>
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi  # EFS scales automatically, but you specify a size for your PVC
