version: '3.8'

services:
  awsbuild:
    image: amd64/ubuntu:<YOUR NAMESPACE HERE>-azdevops-cdp-jammy-img
    container_name: <YOUR NAMESPACE HERE>-aws-ad-auth
    volumes:
      - type: volume
        source: <YOUR NAMESPACE HERE>_awsadauth_vol1
        target: /app
    command: ["tail", "-f", "/dev/null"]

volumes:
  <YOUR NAMESPACE HERE>_awsadauth_vol1:
    external: true
